# Generated by Django 6.0.4 on 2026-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('lokasi', models.CharField(max_length=255)),
                ('daerah', models.CharField(max_length=80)),
                ('keluasan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jenis', models.CharField(max_length=80)),
                ('pbt', models.CharField(blank=True, max_length=120)),
                ('tandas', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('surau', models.BooleanField(default=False)),
                ('deskripsi', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
    ]
