# Generated by Django 6.0.4 on 2026-04-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='taman_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_main_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='taman.taman')),
            ],
            options={
                'ordering': ['-is_main_cover', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='taman',
            name='main_cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='taman.tamanimage'),
        ),
    ]
