# Generated by Django 6.0.4 on 2026-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taman', '0002_tamanimage_taman_main_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taman',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taman',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
