# Generated by Django 6.0.4 on 2026-06-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taman', '0003_daerah_facility_statustanah_auditlog_userprofile'),
        ('taman', '0003_taman_latitude_taman_longitude'),
    ]

    operations = [
    ]
